name: "paraphase"
url: https://github.com/PacificBiosciences/paraphase
description: >
 Run paraphase, organise and merge the outputfiles.
input:
  - bam: bam file
  - fasta: genome fasta file (with .fai index)
  - annotate: gene list, as a “flat” format for which genes to analyse
output:
  - vcf:  vcf file
params:
  - extra: additional parameters that will be forwarded to paraphasse target
authors:
  - Patrik Smeds
